"""Initial migration

Revision ID: 82025bb8a8e4
Revises: 
Create Date: 2026-08-18 10:30:55.042897
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '82025bb8a8e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summary_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('meeting_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_table('meetings',
    sa.Column('fireflies_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('participants', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_date'), 'meetings', ['date'], unique=False)
    op.create_index(op.f('ix_meetings_fireflies_id'), 'meetings', ['fireflies_id'], unique=True)
    op.create_table('meeting_analyses',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('decisions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('client_requests', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('open_questions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('project_status', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_next_actions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_analyses_meeting_id'), 'meeting_analyses', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_analyses_meeting_id'), table_name='meeting_analyses')
    op.drop_table('meeting_analyses')
    op.drop_index(op.f('ix_meetings_fireflies_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_date'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
